spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb1?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:static/*Mapper.xml
  type-aliases-package: com.example.entry